# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master, develop, features/*]
  pull_request:
    branches: [master, develop]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo ${GITHUB_REF}

      - name: Extract branch name
        shell: bash
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"

      - name: Test
        run: echo "${BRANCH_NAME}"

      - name: Extract branch name 2
        shell: bash
        run: echo "::set-env name=BRANCH_NAME2::$(echo ${{ github.ref }} | sed 's/refs\/heads\///g')"

      - name: Test
        run: echo "${BRANCH_NAME2}"

      - name: Extract branch name 3
        shell: bash
        run: echo "::set-env name=BRANCH_NAME3::$(echo ${{ github.ref }} | sed 's/\//_/g')"

      - name: Test
        run: echo "${BRANCH_NAME3}"

      - name: Inspect contexts
        run: |
          echo "The github context is:"
          echo "${{ toJson(github) }}"
          echo ""
          echo "The job context is:"
          echo "${{ toJson(job) }}"
          echo ""
          echo "The steps context is:"
          echo "${{ toJson(steps) }}"
          echo ""
          echo "The runner context is:"
          echo "${{ toJson(runner) }}"
          echo ""
          echo "The strategy context is:"
          echo "${{ toJson(strategy) }}"
          echo ""
          echo "The matrix context is:"
          echo "${{ toJson(matrix) }}"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.          
          ls
    # - name: teste dotnet
    #   run: dotnet --list-sdks
    # - name: Install dotnet SonarScanner a test
    #   run: |
    #     dotnet tool install dotnet-sonarscanner --tool-path . --version 4.7.1
    #     ./dotnet-sonarscanner begin /d:sonar.verbose=true  /k:"wagnerteixeira_test-actions" /n:"Test Actions" /o:"wagnerteixeira" /d:sonar.login=${{ secrets.SONAR_TOKEN }} /d:sonar.host.url=https://sonarcloud.io /d:sonar.cs.opencover.reportsPaths="./tests/TestResults/coverage.opencover.xml" /d:sonar.cs.vstest.reportsPaths="./tests/TestResults/*.trx"
    #     dotnet test --configuration Release /p:CollectCoverage=true /p:CoverletOutput=../TestResults/ /p:CoverletOutputFormat=\"opencover,lcov\" /p:Exclude="[TestActions.Tests*]*" --logger trx --results-directory ./tests/TestResults/
    #     ./dotnet-sonarscanner end /d:sonar.login=${{ secrets.SONAR_TOKEN }}
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
